"""add characters table

Revision ID: 7e7ba8bf7ec1
Revises: e8710dc96cb1
Create Date: 2026-10-05 18:11:57.735520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e7ba8bf7ec1'
down_revision: Union[str, Sequence[str], None] = 'e8710dc96cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=120), nullable=True),
    sa.Column('race_name', sa.String(length=120), nullable=True),
    sa.Column('hp_current', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('rules_edition', sa.Enum('2014', '2024', name='rules_edition'), nullable=False),
    sa.Column('sheet', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sheet_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_index('ix_characters_user_id_deleted_at_updated_at', 'characters', ['user_id', 'deleted_at', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_characters_user_id_deleted_at_updated_at', table_name='characters')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
